# 用于将静态内容部署到 GitHub Pages 的简单工作流
name: Deploy static content to Pages

on:
  # 当 push 到默认分支时运行
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，
# 会跳过排队中的旧任务，仅保留最新任务。
# 但不要取消正在执行中的部署，
# 因为我们希望生产环境部署能够完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 单个部署任务，因为这里只是做部署
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
